- en: 'Enhanced Debugging in Python: Tracebacks Just Got a Major Upgrade'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 原文：[https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38?source=collection_archive---------13-----------------------#2023-03-15](https://towardsdatascience.com/enhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38?source=collection_archive---------13-----------------------#2023-03-15)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: How location-enriched tracebacks facilitate the debugging experience in Python
    3.11
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[![Thomas
    A Dorfer](../Images/9258a1735cee805f1d9b02e2adf01096.png)](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)[](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)[![Towards
    Data Science](../Images/a6ff2676ffcc0c7aad8aaf1d79379785.png)](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    [Thomas A Dorfer](https://thomasdorfer.medium.com/?source=post_page-----bd77fb32db38--------------------------------)'
  prefs: []
  type: TYPE_NORMAL
- en: ·
  prefs: []
  type: TYPE_NORMAL
- en: '[Follow](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F7c54f9b62b90&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fenhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38&user=Thomas+A+Dorfer&userId=7c54f9b62b90&source=post_page-7c54f9b62b90----bd77fb32db38---------------------post_header-----------)
    Published in [Towards Data Science](https://towardsdatascience.com/?source=post_page-----bd77fb32db38--------------------------------)
    ·4 min read·Mar 15, 2023[](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2Fbd77fb32db38&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fenhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38&user=Thomas+A+Dorfer&userId=7c54f9b62b90&source=-----bd77fb32db38---------------------clap_footer-----------)'
  prefs: []
  type: TYPE_NORMAL
- en: --
  prefs: []
  type: TYPE_NORMAL
- en: '[](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2Fbd77fb32db38&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fenhanced-debugging-in-python-tracebacks-just-got-a-major-upgrade-bd77fb32db38&source=-----bd77fb32db38---------------------bookmark_footer-----------)![](../Images/b7116c89ccd139a962a51f3ddcada150.png)'
  prefs: []
  type: TYPE_NORMAL
- en: Photo by [Mohamed Hassan](https://pixabay.com/users/mohamed_hassan-5229782/)
    on [Pixabay](https://pixabay.com/vectors/error-warning-computer-crash-6641731/)
  prefs: []
  type: TYPE_NORMAL
- en: In Python, a traceback is a report that is displayed when an exception occurs,
    along with a (hopefully) helpful error message that can guide the user to the
    problem.
  prefs: []
  type: TYPE_NORMAL
- en: Up until now, tracebacks only showed the line in which the exception occurred,
    but did not provide any location-specific information about which part of that
    line is affected.
  prefs: []
  type: TYPE_NORMAL
- en: 'To illustrate this, let’s assume we have a dictionary object containing some
    summary statistics about some random data. Based on that, we’d like to calculate
    the lower and upper bounds of the confidence interval. This can be done as follows:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: 'I deliberately assigned `None` to the *z*-value in our dictionary object to
    provoke an exception. For Python versions lower than 3.11, this is what the traceback
    would look like:'
  prefs: []
  type: TYPE_NORMAL
