- en: The Catcher in the… Python. Catch Exceptions and Warnings with One Tool
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 原文：[https://towardsdatascience.com/the-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76?source=collection_archive---------19-----------------------#2023-05-23](https://towardsdatascience.com/the-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76?source=collection_archive---------19-----------------------#2023-05-23)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: PYTHON PROGRAMMING
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Why not implement one tool for catching both exceptions and warnings in Python?
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)[![Marcin
    Kozak](../Images/d7faf62e48ed81dab5d8ad92819fff54.png)](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)[](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)[![Towards
    Data Science](../Images/a6ff2676ffcc0c7aad8aaf1d79379785.png)](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)
    [Marcin Kozak](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)'
  prefs: []
  type: TYPE_NORMAL
- en: ·
  prefs: []
  type: TYPE_NORMAL
- en: '[Follow](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F4762f0cff9b2&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&user=Marcin+Kozak&userId=4762f0cff9b2&source=post_page-4762f0cff9b2----81714117da76---------------------post_header-----------)
    Published in [Towards Data Science](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)
    ·13 min read·May 23, 2023[](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2F81714117da76&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&user=Marcin+Kozak&userId=4762f0cff9b2&source=-----81714117da76---------------------clap_footer-----------)'
  prefs: []
  type: TYPE_NORMAL
- en: --
  prefs: []
  type: TYPE_NORMAL
- en: '[](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2F81714117da76&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&source=-----81714117da76---------------------bookmark_footer-----------)![](../Images/6f42c45eba05eb69d8a1a9adcc012803.png)'
  prefs: []
  type: TYPE_NORMAL
- en: The article discusses catching exceptions and warnings in Python. Photo by [Keith
    Johnston](https://unsplash.com/de/@acfb5071?utm_source=medium&utm_medium=referral)
    on [Unsplash](https://unsplash.com/?utm_source=medium&utm_medium=referral)
  prefs: []
  type: TYPE_NORMAL
- en: 'Python has some nice approach to handling exceptions. You can catch them, raise
    them, re-raise them, raise two exceptions at the same time (or rather, one exception
    from another), log them, and to create custom errors and their hierarchy, to name
    just the most important ones. If you want to handle warnings, you can also do
    that — but you need two separate tools: one for exceptions and one for warnings.'
  prefs: []
  type: TYPE_NORMAL
- en: Read this article to learn how to write a single catcher for both exceptions
    and warnings, and how to adjust it to your needs.
  prefs: []
  type: TYPE_NORMAL
- en: 'I really like Python’s exception handling. I like its simplicity, which you
    can see for instance here:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
