["```py\n# packages.yml\n\npackages:\n  - package: dbt-labs/dbt_utils\n    version: 1.1.1\n\n  - package: calogica/dbt_expectations\n    version: 0.8.5\n```", "```py\ndbt test --select tag:contract-test-source\n```", "```py\n1 of 4 START sql table model dbt_testing_example.stg_gym_app__height ........... [RUN]\n2 of 4 START sql table model dbt_testing_example.stg_gym_app__weight ........... [RUN]\n2 of 4 OK created sql table model dbt_testing_example.stg_gym_app__weight ...... [SELECT 4 in 0.88s]\n1 of 4 OK created sql table model dbt_testing_example.stg_gym_app__height ...... [SELECT 4 in 0.92s]\n3 of 4 START sql table model dbt_testing_example.int_weight_measurements_with_latest_height  [RUN]\n3 of 4 OK created sql table model dbt_testing_example.int_weight_measurements_with_latest_height  [SELECT 4 in 0.96s]\n4 of 4 START sql table model dbt_testing_example.body_mass_indexes ............. [RUN]\n4 of 4 ERROR creating sql table model dbt_testing_example.body_mass_indexes .... [ERROR in 0.77s]\n\nFinished running 4 table models in 0 hours 0 minutes and 6.28 seconds (6.28s).\n\nCompleted with 1 error and 0 warnings:\n\nDatabase Error in model body_mass_indexes (models/marts/body_mass_indexes.sql)\n  new row for relation \"body_mass_indexes__dbt_tmp\" violates check constraint \n  \"body_mass_indexes__dbt_tmp_user_id_check1\"\n  DETAIL:  Failing row contains (1, 2009-07-01, 82.5, null, null).\n  compiled Code at target/run/dbt_testing_example/models/marts/body_mass_indexes.sql\n```"]